# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Ohjelmistotuotanto JYU 2024
email: petri.j.ihantola@jyu.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: ''
url: 'https://ohjelmistotuotanto-jyu.github.io'
github_username: ihantola
repo_url: 'https://github.com/ohjelmistotuotanto-jyu/ohjelmistotuotanto-jyu.github.io'
repo_branch: 'master'

norppa: https://forms.office.com/e/m6iaUBkdMc


python_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-jyu/tehtavat'
java_exercise_repo_url: 'https://github.com/ohjelmistotuotanto-jyu/syksy2021-java'


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
